application.id=workflow-scheduler-ecommerce-it
bootstrap.servers=kafka:9092
auto.offset.reset=earliest
cache.max.bytes.buffering=0
state.dir=/tmp/kafka-workflow/scheduler-ecommerce
workflow.scheduler.tick-ms=100
