application.id=workflow-scheduler-trip-booking-saga-it
bootstrap.servers=kafka:9092
auto.offset.reset=earliest
cache.max.bytes.buffering=0
state.dir=/tmp/kafka-workflow/scheduler-trip-booking-saga
workflow.scheduler.tick-ms=100
