application.id=workflow-engine-temporal-mutex-it
bootstrap.servers=kafka:9092
auto.offset.reset=earliest
cache.max.bytes.buffering=0
commit.interval.ms=100
state.dir=/tmp/kafka-workflow/engine-temporal-mutex
